name: reciepts
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
 
 
    
  share_plus: ^12.0.1
  get: ^4.7.3
  pdf: ^3.11.3
  signature: ^6.3.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  file_picker: ^10.3.7
  image_picker: ^1.2.1
 
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path_provider: ^2.1.1
  glassmorphism: ^3.0.0
  animated_text_kit: ^4.3.0
  flutter_animate: ^4.5.2
  google_fonts: ^6.3.3
  data_table_2: ^2.5.15

  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/test_DB/
  fonts:
    - family: OCR-B
      fonts:
        - asset: assets/fonts/OCR-B.otf
    - family: Courier
      fonts:
        - asset: assets/fonts/cour.ttf
