name: reciepts
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
   
  network_info_plus: ^6.1.4
  image: any
  permission_handler: ^12.0.1
    
  share_plus: ^12.0.1
  get: ^4.7.3
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: OCR-B
      fonts:
        - asset: assets/fonts/OCR-B.otf
    - family: Courier
      fonts:
        - asset: assets/fonts/cour.ttf
